--INSERCIONES EN HOTEL--
BEGIN
  INSERT INTO HOTEL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,UBICACION,TIPO_HABITACION)
  VALUES(1,234243,1234,'Calle 93','Suite');
  
  INSERT INTO HOTEL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,UBICACION,TIPO_HABITACION)
  VALUES(2,23452345,3434,'Calle 63','Semi Suite');
  
  INSERT INTO HOTEL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,UBICACION,TIPO_HABITACION)
  VALUES(3,43543,34535,'Calle 34','Estándar');
  
  INSERT INTO HOTEL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,UBICACION,TIPO_HABITACION)
  VALUES(4,12444,12314,'Calle 12','Suite');
  
  INSERT INTO HOTEL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,UBICACION,TIPO_HABITACION)
  VALUES(5,12344,122334,'Calle 54','Semi Suite');
  
  INSERT INTO HOTEL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,UBICACION,TIPO_HABITACION)
  VALUES(6,123423,123123,'Calle 75','Estándar');
  
  INSERT INTO HOTEL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,UBICACION,TIPO_HABITACION)
  VALUES(7,1233324,7734,'Calle 23','Suite');
  
  INSERT INTO HOTEL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,UBICACION,TIPO_HABITACION)
  VALUES(8,6666,6666,'Calle 12','Suite');
  
  INSERT INTO HOTEL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,UBICACION,TIPO_HABITACION)
  VALUES(9,1344,3434,'Calle 54','Estándar');
  
  INSERT INTO HOTEL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,UBICACION,TIPO_HABITACION)
  VALUES(10,23423,23423,'Calle 54','Semi Suite'); 
END;

--INSERCIONES EN HOSTAL--
BEGIN
  INSERT INTO HOSTAL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,TIPO_HABITACION,APERTURA,CIERRE,UBICACION)
  VALUES(1,23243,12334,'Compartida','04:00','22:00','Calle 43');
  
  INSERT INTO HOSTAL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,TIPO_HABITACION,APERTURA,CIERRE,UBICACION)
  VALUES(2,23345,34334,'Sencilla','03:00','22:00','Calle 54');
  
  INSERT INTO HOSTAL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,TIPO_HABITACION,APERTURA,CIERRE,UBICACION)
  VALUES(3,43543,34535,'Sencilla','05:00','23:00','Avenida el Dorado');
  
  INSERT INTO HOSTAL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,TIPO_HABITACION,APERTURA,CIERRE,UBICACION)
  VALUES(4,12444,12314,'Compartida','04:00','22:00','Calle 24');
  
  INSERT INTO HOSTAL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,TIPO_HABITACION,APERTURA,CIERRE,UBICACION)
   VALUES(5,13444,12214,'Compartida','06:00','20:00','Calle 93');
  
  INSERT INTO HOSTAL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,TIPO_HABITACION,APERTURA,CIERRE,UBICACION)
   VALUES(6,13444,12214,'Compartida','06:00','20:00','Calle 93');
  
  INSERT INTO HOSTAL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,TIPO_HABITACION,APERTURA,CIERRE,UBICACION)
   VALUES(7,1232344,12222314,'Compartida','06:00','22:00','Calle 26');
  
  INSERT INTO HOSTAL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,TIPO_HABITACION,APERTURA,CIERRE,UBICACION)
   VALUES(8,33444,22234,'Sencilla','03:00','24:00','Carrera 30');
  
  INSERT INTO HOSTAL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,TIPO_HABITACION,APERTURA,CIERRE,UBICACION)
   VALUES(9,55444,232314,'Compartida','04:00','22:00','Av Boyacá');
  
  INSERT INTO HOSTAL(ID,CAMARA_COMERCIO,SUPERINTENDENCIA,TIPO_HABITACION,APERTURA,CIERRE,UBICACION)
   VALUES(10,34343,23314,'Compartida','06:00','23:00','Calle 11');
  
  
END;

--INSERCIONES HABITACION--
BEGIN
  
  INSERT INTO HABITACION(ID,TIPO_HABITACION,ESPECIAL)
  VALUES(1,'Compartida',1);
  
  INSERT INTO HABITACION(ID,TIPO_HABITACION,ESPECIAL)
  VALUES(2,'Compartida',0);
  
  INSERT INTO HABITACION(ID,TIPO_HABITACION,ESPECIAL)
  VALUES(3,'Compartida',0);
  
  INSERT INTO HABITACION(ID,TIPO_HABITACION,ESPECIAL)
  VALUES(4,'Compartida',0);
  
  INSERT INTO HABITACION(ID,TIPO_HABITACION,ESPECIAL)
  VALUES(5,'Sencilla',1);
  
  INSERT INTO HABITACION(ID,TIPO_HABITACION,ESPECIAL)
  VALUES(6,'Sencilla',0);
  
  INSERT INTO HABITACION(ID,TIPO_HABITACION,ESPECIAL)
  VALUES(7,'Compartida',1);
  
  INSERT INTO HABITACION(ID,TIPO_HABITACION,ESPECIAL)
  VALUES(8,'Sencilla',0);
  
  INSERT INTO HABITACION(ID,TIPO_HABITACION,ESPECIAL)
  VALUES(9,'Compartida',0);
  
  INSERT INTO HABITACION(ID,TIPO_HABITACION,ESPECIAL)
  VALUES(10,'Compartida',1);
  
  
  
END;

--INSERCIONES APARTAMENTO--
BEGIN

INSERT INTO APARTAMENTO(ID,AMOBLADO,COSTO_ADMINISTRACION)
VALUES(1,0,300000);

INSERT INTO APARTAMENTO(ID,AMOBLADO,COSTO_ADMINISTRACION)
VALUES(2,1,230000);

INSERT INTO APARTAMENTO(ID,AMOBLADO,COSTO_ADMINISTRACION)
VALUES(3,1,333000);

INSERT INTO APARTAMENTO(ID,AMOBLADO,COSTO_ADMINISTRACION)
VALUES(4,0,900000);

INSERT INTO APARTAMENTO(ID,AMOBLADO,COSTO_ADMINISTRACION)
VALUES(5,1,700000);

INSERT INTO APARTAMENTO(ID,AMOBLADO,COSTO_ADMINISTRACION)
VALUES(6,1,233333);

INSERT INTO APARTAMENTO(ID,AMOBLADO,COSTO_ADMINISTRACION)
VALUES(7,0,123122);

INSERT INTO APARTAMENTO(ID,AMOBLADO,COSTO_ADMINISTRACION)
VALUES(8,1,888000);

INSERT INTO APARTAMENTO(ID,AMOBLADO,COSTO_ADMINISTRACION)
VALUES(9,0,300000);

INSERT INTO APARTAMENTO(ID,AMOBLADO,COSTO_ADMINISTRACION)
VALUES(10,0,100900);

END;

--INSERCIONES PERSONA--

BEGIN
  
  INSERT INTO PERSONA(ID,NOMBRE,APELLIDO,TIPO,PAPEL,VALOR_MULTA)
  VALUES(1,'Juan','Santos','Estudiante','Usuario',null);
  
  INSERT INTO PERSONA(ID,NOMBRE,APELLIDO,TIPO,PAPEL,VALOR_MULTA)
  VALUES(2,'Flor','Silva','Profesora','Usuario',null);
  
  INSERT INTO PERSONA(ID,NOMBRE,APELLIDO,TIPO,PAPEL,VALOR_MULTA)
  VALUES(3,'Andrés','Fonollosa','Padre','Administrador',null);
  
  INSERT INTO PERSONA(ID,NOMBRE,APELLIDO,TIPO,PAPEL,VALOR_MULTA)
  VALUES(4,'Felipe','Pardo','Estudiante','Usuario',320000);
  
  INSERT INTO PERSONA(ID,NOMBRE,APELLIDO,TIPO,PAPEL,VALOR_MULTA)
  VALUES(5,'Martín','Gómez','Profesor','Administrador',null);
  
  INSERT INTO PERSONA(ID,NOMBRE,APELLIDO,TIPO,PAPEL,VALOR_MULTA)
  VALUES(6,'Camila','Torres','Estudiante','Usuario',89000);
  
  INSERT INTO PERSONA(ID,NOMBRE,APELLIDO,TIPO,PAPEL,VALOR_MULTA)
  VALUES(7,'María','Moreno','Padre','Administrador',null);
  
  INSERT INTO PERSONA(ID,NOMBRE,APELLIDO,TIPO,PAPEL,VALOR_MULTA)
  VALUES(8,'Juan','Moreno','Estudiante','Administrador',null);
  
  INSERT INTO PERSONA(ID,NOMBRE,APELLIDO,TIPO,PAPEL,VALOR_MULTA)
  VALUES(9,'Pedro','Infante','Padre','Administrador',null);
  
  INSERT INTO PERSONA(ID,NOMBRE,APELLIDO,TIPO,PAPEL,VALOR_MULTA)
  VALUES(10,'Vicente','Fernández','Padre','Administrador',null);
  
END;

--INSERCIONES PROPUESTA--

BEGIN
  
  INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVESITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO, HABILITADA)
  VALUES(26,'Habitaci�n Hotel',1,null,1,null,null,null,null,0,4,500000,1);
  
  INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVESITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO, HABILITADA)
  VALUES(27,'Habitaci�n Hotel',2,null,1,null,null,null,null,0,2,1000000,1);
  
  INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVESITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO, HABILITADA)
  VALUES(28,'Habitaci�n Hotel',3,null,1,null,null,null,null,0,6,200000,1);
  
  INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVESITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO, HABILITADA)
  VALUES(29,'Habitaci�n Hotel',3,null,1,null,null,null,null,0,4,800000,1);
  
  INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVESITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO, HABILITADA)
  VALUES(30,'Habitaci�n Hotel',4,null,1,null,null,null,null,0,4,900000,1);
  
  INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOTEl, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (1, 3, 1, 0, 126565, 250000, 'HOTEL',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOTEl, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (2, 5, 2, 0, 126565, 250000, 'HOTEL',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOTEl, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (3 , 3, 3, 0, 126565, 250000, 'HOTEL',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOTEl, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (4, 6, 4, 0, 126565, 250000, 'HOTEL',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOTEl, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (5, 5, 2, 0, 126565, 250000, 'HOTEL',1);

--hostales

INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOSTAL, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (6, 9, 1, 0, 96, 89855785, 'HOSTAL',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOSTAL, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (7, 10, 2, 0, 96, 89855785, 'HOSTAL',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOSTAL, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (8, 5, 3, 0, 96, 89855785, 'HOSTAL',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOSTAL, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (9, 5, 4, 0, 96, 89855785, 'HOSTAL',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOSTAL, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (10, 3, 5, 0, 96, 89855785, 'HOSTAL',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOSTAL, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (11, 9, 6, 0, 96, 89855785, 'HOSTAL',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOSTAL, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (12, 10, 7, 0, 96, 89855785, 'HOSTAL',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOSTAL, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (13, 3, 8, 0, 96, 89855785, 'HOSTAL',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOSTAL, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (14, 5, 9, 0, 96, 89855785, 'HOSTAL',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_HOSTAL, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (15, 6, 10, 0, 96, 89855785, 'HOSTAL',1);


--apartamentos

INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_APARTAMENTO, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (16, 3, 1, 0, 96, 89855785, 'APARTAMENTO',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_APARTAMENTO, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (17, 6, 2, 0, 96, 89855785, 'APARTAMENTO',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_APARTAMENTO, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (18, 6, 3, 0, 96, 89855785, 'APARTAMENTO',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_APARTAMENTO, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (19, 6, 4, 0, 96, 89855785, 'APARTAMENTO',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_APARTAMENTO, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (20, 5, 5, 0, 96, 89855785, 'APARTAMENTO',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_APARTAMENTO, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (21, 9, 6, 0, 96, 89855785, 'APARTAMENTO',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_APARTAMENTO, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (22, 10, 7, 0, 96, 89855785, 'APARTAMENTO',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_APARTAMENTO, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (23, 10, 8, 0, 96, 89855785, 'APARTAMENTO',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_APARTAMENTO, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (24, 6, 9, 0, 96, 89855785, 'APARTAMENTO',1);
INSERT INTO PROPUESTA (ID,ID_PERSONA, ID_APARTAMENTO, SE_RETIRA, CAPACIDAD, COSTO, TIPO_INMUEBLE, HABILITADA ) VALUES (25, 9, 10, 0, 96, 89855785, 'APARTAMENTO',1);
  
END;

--INSERCIONES SERVICIO HOTELERO--

BEGIN
  
  INSERT INTO SERVICIO_HOTELERO(ID,NOMBRE)
  VALUES(1,'Jacuzzi');
  
  INSERT INTO SERVICIO_HOTELERO(ID,NOMBRE)
  VALUES(2,'Piscina');
  
  INSERT INTO SERVICIO_HOTELERO(ID,NOMBRE)
  VALUES(3,'Sauna');
  
  INSERT INTO SERVICIO_HOTELERO(ID,NOMBRE)
  VALUES(4,'Turco');
  
  INSERT INTO SERVICIO_HOTELERO(ID,NOMBRE)
  VALUES(5,'Gimnasio');
  
  INSERT INTO SERVICIO_HOTELERO(ID,NOMBRE)
  VALUES(6,'Zona BBQ');
  
  INSERT INTO SERVICIO_HOTELERO(ID,NOMBRE)
  VALUES(7,'Cancha de Tenis');
  
  INSERT INTO SERVICIO_HOTELERO(ID,NOMBRE)
  VALUES(8,'Cancha de Fútbol');
  
  INSERT INTO SERVICIO_HOTELERO(ID,NOMBRE)
  VALUES(9,'Campo de Golf');
  
  INSERT INTO SERVICIO_HOTELERO(ID,NOMBRE)
  VALUES(10,'Pista');
END;

--INSERCIONES EN TIPO SERVICIO--

BEGIN

INSERT INTO TIPO_SERVICIO(ID,NOMBRE,COSTO)
VALUES(1,'Wi-Fi',50000);

INSERT INTO TIPO_SERVICIO(ID,NOMBRE,COSTO)
VALUES(2,'Lavandería',30000);

INSERT INTO TIPO_SERVICIO(ID,NOMBRE,COSTO)
VALUES(3,'Ascensor',25000);

INSERT INTO TIPO_SERVICIO(ID,NOMBRE,COSTO)
VALUES(4,'Luz',40000);

INSERT INTO TIPO_SERVICIO(ID,NOMBRE,COSTO)
VALUES(5,'Teléfono',15000);

INSERT INTO TIPO_SERVICIO(ID,NOMBRE,COSTO)
VALUES(6,'Direct TV',80000);


END;

--INSERCIONES EN VIVIENDA EXPRESS--

BEGIN
  
  INSERT INTO VIVIENDA_EXPRESS(ID,MENAJE,UBICACION)
  VALUES(1,'Muebles-Cama-TV-Escritorio','Calle 124');
  
  INSERT INTO VIVIENDA_EXPRESS(ID,MENAJE,UBICACION)
  VALUES(2,'Cama-TV-Escritorio','Calle 111');
  
  INSERT INTO VIVIENDA_EXPRESS(ID,MENAJE,UBICACION)
  VALUES(3,'TV-Escritorio','Calle 101');
  
  INSERT INTO VIVIENDA_EXPRESS(ID,MENAJE,UBICACION)
  VALUES(4,'Muebles-Cama-TV','Calle 57');
  
  INSERT INTO VIVIENDA_EXPRESS(ID,MENAJE,UBICACION)
  VALUES(5,'Cama-TV-Escritorio','Calle 93');
  
  INSERT INTO VIVIENDA_EXPRESS(ID,MENAJE,UBICACION)
  VALUES(6,'Muebles-Cama-TV-Escritorio','Calle 54');
  
  INSERT INTO VIVIENDA_EXPRESS(ID,MENAJE,UBICACION)
  VALUES(7,'Cama-TV-Escritorio','Calle 44');
  
  INSERT INTO VIVIENDA_EXPRESS(ID,MENAJE,UBICACION)
  VALUES(8,'Muebles-Cama-TV-Escritorio','Calle 94');
  
  INSERT INTO VIVIENDA_EXPRESS(ID,MENAJE,UBICACION)
  VALUES(9,'Muebles-Cama-TV-Escritorio','Calle 85');
  
  INSERT INTO VIVIENDA_EXPRESS(ID,MENAJE,UBICACION)
  VALUES(10,'Muebles-Cama-TV-Escritorio','Calle 24');
END;

--INSERCIONES EN VIVIENDA UNIVERSITARIA--

BEGIN

INSERT INTO VIVIENDA_UNIVERSITARIA(ID,TIPO_HABITACION,MENAJE,MENSUAL,DESCRIPCION)
VALUES(1,'Sencilla','Tv-Escritorio-Cocina',1,'Vivienda ubicada en city U');

INSERT INTO VIVIENDA_UNIVERSITARIA(ID,TIPO_HABITACION,MENAJE,MENSUAL,DESCRIPCION)
VALUES(2,'Compartida','Tv-Escritorio-Cocina',0,'Vivienda ubicada en Livinn');

INSERT INTO VIVIENDA_UNIVERSITARIA(ID,TIPO_HABITACION,MENAJE,MENSUAL,DESCRIPCION)
VALUES(3,'Compartida','Tv-Escritorio',0,'Vivienda ubicada en city U');

INSERT INTO VIVIENDA_UNIVERSITARIA(ID,TIPO_HABITACION,MENAJE,MENSUAL,DESCRIPCION)
VALUES(4,'Compartida','Tv-Escritorio-Closet',0,'Vivienda ubicada en city U');

INSERT INTO VIVIENDA_UNIVERSITARIA(ID,TIPO_HABITACION,MENAJE,MENSUAL,DESCRIPCION)
VALUES(5,'Sencilla','Tv-Escritorio-Closet',0,'Vivienda ubicada en city U');

INSERT INTO VIVIENDA_UNIVERSITARIA(ID,TIPO_HABITACION,MENAJE,MENSUAL,DESCRIPCION)
VALUES(6,'Sencilla','Tv-Escritorio-Cocina',1,'Vivienda ubicada en Livinn');

INSERT INTO VIVIENDA_UNIVERSITARIA(ID,TIPO_HABITACION,MENAJE,MENSUAL,DESCRIPCION)
VALUES(7,'Sencilla','Tv-Escritorio-Cocina',1,'Vivienda ubicada en Livinn');

INSERT INTO VIVIENDA_UNIVERSITARIA(ID,TIPO_HABITACION,MENAJE,MENSUAL,DESCRIPCION)
VALUES(8,'Compartida','Tv-Escritorio-Closet',0,'Vivienda ubicada en BD Bacatá');

INSERT INTO VIVIENDA_UNIVERSITARIA(ID,TIPO_HABITACION,MENAJE,MENSUAL,DESCRIPCION)
VALUES(9,'Sencilla','Tv-Escritorio-Closet',0,'Vivienda ubicada en BD Bacatá');

INSERT INTO VIVIENDA_UNIVERSITARIA(ID,TIPO_HABITACION,MENAJE,MENSUAL,DESCRIPCION)
VALUES(10,'Sencilla','Tv-Escritorio-Cocina',0,'Vivienda ubicada en BD Bacatá');
END;
--INSERCIONES EN SERVICIO BASICO--
INSERT INTO "ISIS2304A901810"."SERVICIO_BASICO" (ID, ID_TIPO_SERVICIO, ID_APARTAMENTO, ID_HABITACION, ID_VIVIENDA_EXPRESS, COLUMN1) VALUES ('2', '1', '2', '2', '2', '2')
INSERT INTO "ISIS2304A901810"."SERVICIO_BASICO" (ID, ID_TIPO_SERVICIO, ID_APARTAMENTO) VALUES ('3', '2', '1')
INSERT INTO "ISIS2304A901810"."SERVICIO_BASICO" (ID, ID_TIPO_SERVICIO, ID_APARTAMENTO) VALUES ('4', '2', '2')
INSERT INTO "ISIS2304A901810"."SERVICIO_BASICO" (ID, ID_TIPO_SERVICIO, ID_APARTAMENTO) VALUES ('5', '1', '3')

--INSERCIONES EN PROPUESTA--


INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVERSITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO)
VALUES(1,'Hotel',3,null,1,null,null,null,null,0,2,100000);

INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVERSITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO)
VALUES(2,'Hotel',3,null,2,null,null,null,null,0,3,150000);

INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVERSITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO)
VALUES(3,'Hotel',5,null,3,null,null,null,null,0,2,200000);

INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVERSITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO)
VALUES(4,'Hotel',5,null,4,null,null,null,null,0,3,233999);

INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVERSITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO)
VALUES(5,'Hotel',8,null,5,null,null,null,null,0,3,100000);

INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVERSITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO)
VALUES(6,'Hotel',8,null,6,null,null,null,null,0,3,100000);

INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVERSITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO)
VALUES(7,'Hotel',8,null,7,null,null,null,null,0,5,500000);

INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVERSITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO)
VALUES(8,'Hotel',9,null,8,null,null,null,null,0,3,299999);

INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVERSITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO)
VALUES(9,'Hotel',9,null,9,null,null,null,null,0,1,75000);

INSERT INTO PROPUESTA(ID,TIPO_INMUEBLE,ID_PERSONA,ID_HOSTAL,ID_HOTEL,ID_VIVIENDA_EXPRESS,ID_VIVIENDA_UNIVERSITARIA,ID_APARTAMENTO,ID_HABITACION,SE_RETIRA,CAPACIDAD,COSTO)
VALUES(10,'Hotel',9,null,10,null,null,null,null,0,3,200000); 

--SENTENCIAS--
SELECT * FROM PROPUESTA PRO 
WHERE UPPER(TIPO_INMUEBLE) =UPPER('Apartamento')
AND PRO.ID_APARTAMENTO
IN ( SELECT SERV.ID_APARTAMENTO 
FROM SERVICIO_BASICO SERV 
INNER JOIN TIPO_SERVICIO 
TI ON TI.ID = SERV.ID_TIPO_SERVICIO
WHERE TI.NOMBRE IN ('Lavandería','Wi-Fi'));