
--SERVICIO_BASICO--
ALTER TABLE SERVICIO_BASICO ADD FOREIGN KEY (ID_TIPO_SERVICIO) REFERENCES TIPO_SERVICIO (ID);
ALTER TABLE SERVICIO_BASICO ADD FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION (ID);
ALTER TABLE SERVICIO_BASICO ADD FOREIGN KEY (ID_VIVIENDA_UNIVERSITARIA) REFERENCES VIVIENDA_UNIVERSITARIA (ID);
ALTER TABLE SERVICIO_BASICO ADD FOREIGN KEY (ID_APARTAMENTO) REFERENCES APARTAMENTO (ID);
ALTER TABLE SERVICIO_BASICO ADD FOREIGN KEY (ID_VIVIENDA_EXPRESS) REFERENCES VIVIENDA_EXPRESS (ID);

--HOTEL_HAS_SERVICIOS--
ALTER TABLE HOTEL_HAS_SERVICIOS ADD FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL(ID);
ALTER TABLE HOTEL_HAS_SERVICIOS ADD FOREIGN KEY (ID_HOSTAL) REFERENCES HOSTAL(ID);
ALTER TABLE HOTEL_HAS_SERVICIOS ADD FOREIGN KEY (ID_SERVICIO_HOTELERO) REFERENCES SERVICIO_HOTELERO(ID);


--PROPUESTA--
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID);
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL (ID);
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_HOSTAL) REFERENCES HOSTAL (ID);
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_VIVIENDA_EXPRESS) REFERENCES VIVIENDA_EXPRESS (ID);
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_APARTAMENTO) REFERENCES APARTAMENTO (ID);
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_VIVIENDA_UNIVERSITARIA) REFERENCES VIVIENDA_UNIVERSITARIA (ID);
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION (ID);

--RESERVAS--
ALTER TABLE RESERVA ADD FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID);
ALTER TABLE RESERVA ADD FOREIGN KEY (ID_PROPUESTA) REFERENCES PROPUESTA (ID