-- 
-- 
-- CREAR
-- 
-- 


-- crea la tabla PERSONAS
CREATE TABLE PERSONA (
    ID INT, 
    NOMBRE VARCHAR(25), 
    APELLIDO VARCHAR(25), 
    TIPO VARCHAR(25),
    PAPEL VARCHAR(25),
    VALOR_MULTA INT,
);

-- crea la tabla RESERVAS
CREATE TABLE RESERVA ( 
    ID INT, 
    ID_PROPUESTA INT,
    ID_PERSONA INT, 
    FECHA_REGISTRO VARCHAR(25), 
    FECHA_INICIO VARCHAR(25), 
    FECHA_CANCELACION VARCHAR(25), 
    COSTO DOUBLE,
    DURACION INT, 
    PERSINAS INT,
    MULTA DOUBLE,
    ID_COLLECTIVO INT
);

-- crea la tabla PROPUESTAS
create table PROPUESTA (
	ID INT,
	TIPO_INMUEBLE VARCHAR(25),
    ID_PERSONA INT,
	ID_HOSTAL INT,
	ID_HOTEL INT,
	ID_VIVIENDA_EXPRESS INT,
	ID_VIVIENDA_UNIVERSITARIA INT,
	ID_APARTAMENTO INT,
	ID_HABITACION INT,
    SE_RETIRA INT,
    CAPACIDAD INT,
    COSTO DOUBLE,
    HABILITADA INT
    
);

--crea tabla de normalizacion
create table PROPUESTA_DESHABILITADA (
	ID_PROPUESTA INT,
	FECHA_INICIO_DESHABILITADA VARCHAR(25),
    FECHA_FIN_DESHABILITADA VARCHAR(25)

);

-- crea la tabla HOTELES
CREATE TABLE HOTEL ( 
    ID INT, 
    CAMARA_COMERCIO VARCHAR(500), 
    SUPERINTENDENCIA VARCHAR(500), 
    UBICACION VARCHAR(50),
);

-- crea la tabla HOSTELES
CREATE TABLE HOSTAL ( 
    ID INT, 
    CAMARA_COMERCIO VARCHAR(500), 
    SUPERINTENDENCIA VARCHAR(500),
    TIPO_HABITACION VARCHAR(25), 
    APERTURA INT, 
    CIERRE INT, 
    UBICACION VARCHAR(50), 
);


-- crea tabla HOTEL_TIENE_SERVICIOS
CREATE TABLE HOTEL_HAS_SERVICIOS (
    ID_SERVICIO_HOTELERO INT,
    ID_HOTEL INT, 
    ID_HOSTAL INT 
);

-- crea tabla SERVICIOS_BASICOS_HOTELEROS
CREATE TABLE SERVICIO_HOTELERO ( 
    ID INT, 
    NOMBRE VARCHAR(25)
);

-- crea tabla VIVIENDA_EXPRESS
CREATE TABLE VIVIENDA_EXPRESS ( 
    ID INT, 
    MENAJE VARCHAR(200) , 
    UBICACION VARCHAR(50)
);

-- crea tabla APARTAMENTOS
CREATE TABLE APARTAMENTO ( 
    ID INT, 
    AMOBLADO NUMBER(1,0), 
    COSTO_ADMINISTRACION FLOAT 
);

-- crea tabla VIVIENDA_UNIVERITARIA
CREATE TABLE VIVIENDA_UNIVERSITARIA ( 
    ID INT, 
    TIPO_HABITACION VARCHAR(25), 
    MENSUAL NUMBER(1,0), 
    MENAJE VARCHAR(200), 
    DESCRIPCION VARCHAR(200) 
 
);

-- crea tabla HABITACION 
CREATE TABLE HABITACION ( 
    ID INT, 
    TIPO_HABITACION VARCHAR(25),
    ESPECIAL NUMBER(1,0)
);

-- Crea tabla SERVICIOS_BASICOS
CREATE TABLE SERVICIO_BASICO ( 
    ID INT, 
    ID_TIPO_SERVICIO INT, 
    ID_APARTAMENTO INT, 
    ID_HABITACION INT, 
    ID_VIVIENDA_EXPRESS INT 
    ID_VIVIENDA_UNIVERSITARIA INT, 
);

-- crea tabla TIPOS de servicio basico
CREATE TABLE TIPO_SERVICIO ( 
    ID INT, 
    NOMBRE VARCHAR(25), 
    COSTO DOUBLE 
);









-- 
-- 
-- ALTERAR
-- 
-- 


-- PERSONAS
ALTER TABLE PERSONA ADD PRIMARY KEY (ID);
ALTER TABLE PERSONA MODIFY NOMBRE VARCHAR(25) NOT NULL;
ALTER TABLE PERSONA MODIFY APELLIDO VARCHAR(25) NOT NULL;
ALTER TABLE PERSONA MODIFY TIPO VARCHAR(25) DEFAULT 'normal';
ALTER TABLE PERSONA MODIFY ROL VARCHAR(25) DEFAULT 'cliente';
ALTER TABLE PERSONA MODIFY NIT DEFAULT NULL;


-- HOTELES
ALTER TABLE HOTEL ADD PRIMARY KEY (ID);
ALTER TABLE HOTEL MODIFY REGISTRO_CAMARA_COMERCIO NOT NULL;
ALTER TABLE HOTEL MODIFY REGISTRO_SUPERINTENDENCIA NOT NULL;
ALTER TABLE HOTEL  add constraint TIPOS check (TIPO_HABITACION in ('estandar', 'semisuite', 'suite'));
ALTER TABLE HOTEL add constraint TAMANOS check (TAMANO in ('grande', 'mediano', 'pequeño'));

-- HOTELES
ALTER TABLE HOSTAL ADD PRIMARY KEY (ID);
ALTER TABLE HOSTAL MODIFY REGISTRO_CAMARA_COMERCIO TEXT NOT NULL;
ALTER TABLE HOSTAL MODIFY REGISTRO_SUPERINTENDENCIA TEXT NOT NULL;
ALTER TABLE HOSTAL  add constraint HORARIO_I_CHEK CHECK ( HORARIO_ADMIN_INICIAL >=  0 AND HORARIO_ADMIN_INICIAL <=  24);
ALTER TABLE HOSTAL ADD CONSTRAINT HORARIO_F_CHECK CHECK ( HORARIO_ADMIN_FINAL >=  0 AND HORARIO_ADMIN_FINAL <=  24);
ALTER TABLE HOSTAL  ADD CONSTRAINT  HORARIO_CHEK  CHECK ( HORARIO_ADMIN_INICIAL < HORARIO_ADMIN_FINAL );
ALTER TABLE HOSTAL  add constraint TIPO_HAB check (TIPO_HABITACION in ('compartida', 'sencilla'));

-- SERVICIOS_BASICOS_HOTELEROS
ALTER TABLE SERVICIO_HOTELERO ADD PRIMARY KEY (ID);

-- HOTEL_TIENE_SERVICIOS
ALTER TABLE HOTEL_HAS_SERVICIOS ADD FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL(ID);
ALTER TABLE HOTEL_HAS_SERVICIOS ADD FOREIGN KEY (ID_HOSTAL) REFERENCES HOSTAL(ID);
ALTER TABLE HOTEL_HAS_SERVICIOS ADD FOREIGN KEY (ID_SERVICIO_BASICO_HOTELERO) REFERENCES SERVICIO_HOTELERO(ID);

-- VIVIENDA_EXPRESS
ALTER TABLE VIVIENDA_EXPRESS ADD PRIMARY KEY (ID);

-- APARTAMENTO
ALTER TABLE APARTAMENTO ADD PRIMARY KEY (ID);

-- VIVIENDA_UNIVERSITARIA
ALTER TABLE VIVIENDAS_UNIVERSITARIA ADD PRIMARY KEY (ID);

-- HABIACION 
ALTER TABLE HABITACION ADD PRIMARY KEY (ID);

-- TIPO
ALTER TABLE TIPO_SERVICIO ADD PRIMARY KEY (ID);
ALTER TABLE TIPO_SERVICIO MODIFY COSTO DEFAULT NULL;

-- SERVICIOS_BASICOS
ALTER TABLE SERVICIO_BASICO ADD PRIMARY KEY (ID);
ALTER TABLE SERVICIO_BASICO ADD FOREIGN KEY (ID_TIPO) REFERENCES TIPO_SERVICIO (ID);
ALTER TABLE SERVICIO_BASICO ADD FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION (ID);
ALTER TABLE SERVICIO_BASICO ADD FOREIGN KEY (ID_VIVIENDA_UNIVERSITARIA) REFERENCES VIVIENDAS_UNIVERSITARIA (ID);
ALTER TABLE SERVICIO_BASICO ADD FOREIGN KEY (ID_APARTAMENTO) REFERENCES APARTAMENTO (ID);
ALTER TABLE SERVICIO_BASICO ADD FOREIGN KEY (ID_VIVIENDA_EXPRESS) REFERENCES VIVIENDA_EXPRESS (ID);

-- PROPUESTAS
ALTER TABLE PROPUESTA ADD PRIMARY KEY (ID);
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID);
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL (ID);
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_HOSTAL) REFERENCES HOSTAL (ID);
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_VIVIENDA_EXPRESS) REFERENCES VIVIENDA_EXPRESS (ID);
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_APARTAMENTO) REFERENCES APARTAMENTO (ID);
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_VIVIENDA_UNIVERSITARIA) REFERENCES VIVIENDAS_UNIVERSITARIA (ID);
ALTER TABLE PROPUESTA ADD FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION (ID);

-- RESERVAS
ALTER TABLE RESERVA ADD PRIMARY KEY (ID);
ALTER TABLE RESERVA ADD FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID);
ALTER TABLE RESERVA MODIFY FECHA_CANCELACION VARCHAR(25) DEFAULT NULL;
ALTER TABLE RESERVA ADD FOREIGN KEY (ID_PROPUESTA) REFERENCES PROPUESTA (ID);

--PROPUESTA DESHABILITADA
ALTER TABLE PROPUESTA_DESHABILITADA ADD FOREIGN KEY (ID_PROPUESTA) REFERENCES PROPUESTA (ID);
